express = require('express')
git     = require('nodegit')
path    = require('path')

repoRoot    = path.resolve(process.env.REPO_ROOT || path.join(__dirname, '..', '..'))
load        = require('./util/load')(repoRoot)
url         = require('./util/url')

refs        = require('./routes/refs')
treeEntries = require('./routes/tree_entries')
blobs       = require('./routes/blobs')
commits     = require('./routes/commits')
repo        = require('./routes/repos')

app = express()
app.use(express.responseTime())
app.use(express.compress())
app.use(express.bodyParser())
app.use(express.methodOverride())
app.set('view engine', 'ejs')
app.set('views', __dirname + '/views')
app.locals.url = url

app.get(url.repo(),               [load.repo],                                                                repo.show)
app.get(url.refs(),               [load.repo],                                                                refs.index)
app.get(url.headRef(),            [load.repo, load.headRef],                                                  refs.show)
app.get(url.tagRef(),             [load.repo, load.tagRef],                                                   refs.show)
app.get(url.remoteRef(),          [load.repo, load.remoteRef],                                                refs.show)
app.get(url.headRefCommits(),     [load.repo, load.headRef, load.ref2commit],                                 commits.index)
app.put(url.headRefCommits(),     [load.repo, load.headRef, load.ref2commit],                                 commits.create)
app.get(url.tagRefCommits(),      [load.repo, load.tagRef, load.ref2commit],                                  commits.index)
app.get(url.remoteRefCommits(),   [load.repo, load.remoteRef, load.ref2commit],                               commits.index)
app.get(url.headRefTreeEntry(),   [load.repo, load.headRef, load.ref2commit, load.commit2tree, load.entry],   treeEntries.show)
app.get(url.remoteRefTreeEntry(), [load.repo, load.remoteRef, load.ref2commit, load.commit2tree, load.entry], treeEntries.show)
app.get(url.tagRefTreeEntry(),    [load.repo, load.tagRef, load.ref2commit, load.commit2tree, load.entry],    treeEntries.show)
app.get(url.blob(),               [load.repo, load.blob],                                                     blobs.show)
app.put(url.commits(),            [load.repo],                                                                commits.create)
app.get(url.commit(),             [load.repo, load.commit],                                                   commits.show)
app.get(url.commitTreeEntry(),    [load.repo, load.commit, load.commit2tree, load.entry],                     treeEntries.show)
app.get('/', (req, res) -> res.render('index.html.ejs'))

module.exports = app